### PR TITLE
Make JSON names comply with lower-case first-letter name rules

### PR DESCRIPTION
**Pull request by jbuberel**
Most JSON style guides recommend lower-case first letters (especially Google's - https://google-styleguide.googlecode.com/svn/trunk/jsoncstyleguide.xml).

What do you think of making all of these lower-case on the JSON structure in order to comply?

### CODE REVIEW

**Comment by kardianos** [comment]
That's probably fine. When in Rome...

I'm hesitant to use the field tags in this definition rather then just changing the case. This struct definition shouldn't be used directly due to the requirement to preserve unknown fields; map[string]interface{} should be used.

I'm fine merging as is. Leaving for now for opinion(s).

**Comment by jbuberel** [comment]
I have a second pull request lined up that adds the `json:"field"` tags :-)

Jason L. Buberel
jason@buberel.org

**Comment by ngrilly** [comment]
Are you sure about this? Considering that the file will be read mostly in the context of a Go program, capitalizing the first letter is simpler and "alien" norms doesn't necessarily apply.

**Comment by jbuberel** [comment]
A couple of the members of the Go team requested the change, most likely
because they're accustomed to all JSON conforming to the Google JSON style
guide:

https://google-styleguide.googlecode.com/svn/trunk/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format

Jason L. Buberel
jason@buberel.org

**Pull request merged**
